const assert = require("node:assert/strict");
module.exports = async (page, go, field, click, save, shot) => {
  await go("overview", "current"); await page.getByRole("link", { name: "日程生成参数", exact: true }).click();
  await page.locator('#section-panel[data-section="settings"][data-page="schedule"]').waitFor();
  await go("overview", "current"); await page.getByRole("link", { name: "完整日程", exact: true }).click();
  await page.locator('#section-panel[data-section="timeline"]').waitFor();
  await go("character", "drives"); await page.getByRole("link", { name: "模块启停设置", exact: true }).click();
  await page.locator('#section-panel[data-page="system"][data-section="modules"]').waitFor();
  await go("context", "usage"); await field("context_usage.limits.memory.knowledge").fill("8"); await field("context_usage.brief_max_chars.memory.journal").fill("180");
  const usageSource = page.locator('.context-usage-row').first().getByRole('button', { name: /来源$/ });
  await usageSource.click();
  await page.locator('#source-index').getByRole('button', { name: '07 记忆与日记 → 记忆与人物 → 知识记忆', exact: true }).click();
  assert.equal(await field('memory.kind').inputValue(), 'memory.knowledge');
  await click('返回上下文用量');
  assert.equal(await field("context_usage.limits.memory.knowledge").inputValue(), "8");
  await page.evaluate(() => { window.failNext = true; }); await click("保存上下文用量");
  await page.getByText("测试来源暂时不可用", { exact: true }).waitFor();
  await click("刷新数据");
  assert.equal(await field("context_usage.limits.memory.knowledge").inputValue(), "8");
  await go("memory", "records"); await go("context", "usage"); assert.equal(await field("context_usage.limits.memory.knowledge").inputValue(), "8");
  await save("保存上下文用量");
  const usagePatch = await page.evaluate(() => window.calls.findLast(c => c.endpoint === "settings" && c.method === "POST").body);
  assert.deepEqual(Object.keys(usagePatch), ["context_usage"]);
  assert.equal(usagePatch.context_usage.limits["memory.knowledge"], 8);
  assert.equal(usagePatch.context_usage.brief_max_chars["memory.journal"], 180);
  assert.equal(usagePatch.context_usage.brief_max_chars["memory.notes"], 200);
  assert.match(await page.locator(".context-usage-total").textContent(), /32 条/);
  const savedCalls = await page.evaluate(() => window.calls.length);
  await click("恢复初始用量");
  assert.match(await page.locator(".context-usage-total").textContent(), /28 条/);
  assert.equal(await field("context_usage.brief_max_chars.memory.journal").inputValue(), "200");
  assert.equal(await page.evaluate(() => window.calls.length), savedCalls);
  await field("context_usage.limits.memory.knowledge").fill("0");
  assert.match(await page.locator(".context-usage-total").textContent(), /24 条/);
  await field("context_usage.limits.memory.knowledge").fill("8");
  await field("context_usage.brief_max_chars.memory.journal").fill("180");
  assert.equal(await page.locator('.context-usage-row').count(), 10);
  assert.equal(await page.locator('.context-usage-row .layout-source').count(), 10);
  assert.ok((await page.locator('.context-usage-row').evaluateAll(rows => rows.map(row => row.getBoundingClientRect().height))).every(height => height <= 44));
  await shot("context-usage-desktop");
  await go("memory", "records");
  await field("memory.kind").selectOption("");
  await page.locator('[data-record-id="m1"] input[type=checkbox]').check();
  await page.locator('[data-record-id="m3"] input[type=checkbox]').check(); await click("合并所选");
  await page.getByText("只能合并同一场合的记忆，避免把私人内容带到其他场合。", { exact: true }).waitFor();
  await page.locator('[data-record-id="m3"] input[type=checkbox]').uncheck();
  await page.locator('[data-record-id="m2"] input[type=checkbox]').check(); await click("合并所选");
  await page.locator("#editor[open]").waitFor(); await page.locator("#editor-cancel").click();
  await page.locator('[data-record-id="m1"]').getByRole("button", { name: "编辑", exact: true }).click();
  assert.match(await page.locator("#editor-body").textContent(), /编辑保留原有场合与人物/);
  assert.equal(await page.locator('#editor [name="scope"]').count(), 0);
  await page.locator("#editor-cancel").click();
  // All large archives page at ten records; opening text is deliberate.
  await page.evaluate(() => {
    for (const key of ["memories", "events", "observations", "entries", "deliveries"]) window.recordBackups ||= {}, window.recordBackups[key] = structuredClone(window.fixture[key]);
    for (const key of Object.keys(window.recordBackups)) window.fixture[key] = Array.from({ length: 23 }, (_, i) => ({ id: `${key}-${i}`, title: `记录 ${i}：` + "长名称".repeat(30), text: `详细正文 ${key} ${i}`, scope: i % 2 ? "global" : "qq:FriendMessage:42", kind: key === "entries" ? "journal" : "event", module: "news", created_at: 1800000000 + i }));
  }); await click("刷新数据");
  for (const [name, tab, key] of [["character", "events", "events"], ["memory", "records", "memories"], ["sources", "records", "observations"], ["memory", "journals", "journals"], ["chat", "deliveries", "deliveries"]]) {
    await go(name, tab); if (name === "sources") await field("source.records").selectOption("");
    if (key === "journals") await field("journals.kind").selectOption("");
    assert.equal(await page.locator(".compact-record-row").count(), 10, `${name}/${tab} defaults to ten`);
    await click("下一页"); assert.equal(await page.locator(".compact-record-row").count(), 10);
    await click("下一页"); assert.equal(await page.locator(".compact-record-row").count(), 3);
    await field(key + ".search").fill("详细正文"); await go("overview", "current"); await go(name, tab);
    assert.equal(await field(key + ".search").inputValue(), "详细正文");
    await page.locator(".record-open").first().click(); await page.locator("#editor[open]").waitFor();
    if (key === "journals") await page.locator("#editor summary").click();
    assert.match(await page.locator("#editor-body").textContent(), /详细正文/); await page.locator("#editor-cancel").click();
    await field(key + ".scope").selectOption("global");
    assert.match(await page.locator(".pagination").textContent(), /11 条/);
    await field(key + ".scope").selectOption(""); await field(key + ".search").fill("");
  }
  await page.evaluate(() => { Object.assign(window.fixture, window.recordBackups); }); await click("刷新数据");
  await go("memory", "journals"); await click("生成简报"); await page.locator("#editor-submit").click();
  await page.getByText("操作已完成，请查看执行结果", { exact: true }).waitFor();
  await page.locator(".record-open").first().click(); assert.match(await page.locator("#editor-body").textContent(), /简报：看到了星星/);
  assert.equal(await page.evaluate(() => window.briefXss), undefined); await page.locator("#editor-cancel").click();
  await go("schedule", "settings"); await field("life.activity_count").fill("11"); await go("schedule", "timeline"); await click("重新生成日程");
  await page.getByText("请先保存日程设置，再重新生成日程。", { exact: true }).waitFor();
  await go("schedule", "settings"); await field("life.activity_count").fill("10"); await save("保存日程设置");
  assert.equal(await page.evaluate(() => window.calls.some(c => c.body?.action === "regenerate_day")), false);
  await go("schedule", "timeline"); assert.equal(await page.locator(".timeline .record").count(), 10);
  await click("重新生成日程"); await page.locator("#editor-submit").click();
  await page.getByText("操作已完成，请查看执行结果", { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.fixture.life_day_history.length), 1);
  await go("schedule", "archives"); await page.getByText("生成输入快照（非 API 原文）", { exact: true }).waitFor();
  await page.getByText("模型生成的日程文本", { exact: true }).waitFor();
  await go("schedule", "timeline"); await page.getByLabel("日程日期").fill(await page.evaluate(() => window.testTomorrow));
  await page.getByLabel("日程日期").dispatchEvent("change"); await click("细化活动");
  await page.locator('#editor [name="instruction"]').fill("专心学习，不安排聊天。");
  await page.evaluate(() => { window.failNext = true; }); await page.locator("#editor-submit").click();
  await page.getByText("测试来源暂时不可用", { exact: true }).waitFor();
  assert.equal(await page.locator('#editor [name="instruction"]').inputValue(), "专心学习，不安排聊天。");
  await page.locator("#editor-submit").click(); await page.getByText("操作已完成，请查看执行结果", { exact: true }).waitFor();
  await page.getByText("细化与执行详情", { exact: true }).click(); assert.match(await page.locator(".activity-detail").textContent(), /专心学习|函数/);
  await click("重新细化"); await page.locator('#editor [name="instruction"]').fill("再复习一遍。"); await page.locator("#editor-submit").click();
  await page.getByText("操作已完成，请查看执行结果", { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.fixture.detail_history.length), 1);
  await click("编辑"); await page.locator('#editor [name="title"]').fill("新的大纲标题"); await page.locator("#editor-submit").click();
  await page.getByText("操作已完成，请查看执行结果", { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.fixture.activities.find(row => row.id === "future").detailed), false);
  await page.evaluate(() => { window.fixture.life_days[0].full_request._debug_record_id = "chat-step-3"; window.fixture.debug_views[0].record_ids = ["chat-step-3"]; });
  await page.getByLabel("日程日期").fill(await page.evaluate(() => window.fixture.life_days[0].date)); await page.getByLabel("日程日期").dispatchEvent("change");
  await click("刷新数据"); await go("schedule", "archives"); await page.getByRole("link", { name: "查看这次调用的 API 原文", exact: true }).click();
  await page.locator('.debug-round[data-turn="round-1"]').waitFor();
  await go("context", "calls", { turn: "cleaned-record" }); await page.getByText("这次调用的调试记录已清理或尚未产生；正式档案仍保留。", { exact: true }).waitFor();
  await go("character", "drives"); await shot("drives-desktop");
};
