const assert = require("node:assert/strict");
module.exports = async (page, go, backendContract) => {
 const rootFolds = (entry) => entry.locator(".debug-json-document > .debug-json-node");
 const foldToggle = (node) => node.locator(":scope > .debug-json-toggle");
    await go("context", "calls");
    await page.locator('[name="debug_round"]').selectOption("round-1");
    const round = page.locator('.debug-round[data-turn="round-1"]');
    assert.equal(await page.locator('.debug-round').count(), 1);
    assert.equal(await round.getAttribute("open"), "");
    assert.equal(await round.getByRole("tab").count(), 4);
    assert.ok((await round.innerText()).includes("Living World 今日日程 · 本次私聊"));
    assert.ok((await round.innerText()).includes("插件实际加入的完整文本"));
    const sourceCards = round.locator(".debug-sources > details.debug-source");
    assert.equal(await sourceCards.count(), 3);
    assert.equal(await sourceCards.evaluateAll((cards) => cards.every((card) => card.open)), true, "Sources start expanded");
    const assertSingleColumnSources = async () => {
      const boxes = await sourceCards.evaluateAll((cards) => cards.map((card) => { const box = card.getBoundingClientRect(); return { x: box.x, y: box.y, width: box.width, bottom: box.bottom }; }));
      for (let index = 1; index < boxes.length; index++) {
        assert.ok(Math.abs(boxes[index].x - boxes[0].x) < 1 && Math.abs(boxes[index].width - boxes[0].width) < 1, "Every source occupies the same full-width column");
        assert.ok(boxes[index].y >= boxes[index - 1].bottom, "Sources stack vertically");
      }
    };
    await assertSingleColumnSources();
    await sourceCards.first().locator("summary").click();
    assert.equal(await sourceCards.first().getAttribute("open"), null);
    await sourceCards.first().getByText("当前日程", { exact: true }).waitFor();
    await sourceCards.first().getByText("来源：Living World 今日日程 · 本次私聊 · 放入：本轮末尾", { exact: true }).waitFor();
    assert.equal(await sourceCards.first().locator(".debug-source-content").isVisible(), false);
    assert.equal(await sourceCards.nth(1).getAttribute("open"), "", "Collapsing one source leaves the next expanded");
    await sourceCards.first().locator("summary").focus();
    await page.keyboard.press("Enter");
    assert.equal(await sourceCards.first().getAttribute("open"), "", "Native source disclosures support keyboard operation");
    await sourceCards.first().locator("summary").click();
    assert.equal(await page.evaluate(() => window.debugXss), undefined);
    assert.equal(await round.locator("img").count(), 0);
    assert.ok(!(await round.innerText()).includes("个步骤"));
    assert.equal(await page.locator('#navigation a').nth(1).getAttribute("data-view"), "context");
    assert.ok((await page.locator('#navigation a').nth(1).innerText()).startsWith("02"));
    const downloadedText = async (trigger) => {
      const downloadPromise = page.waitForEvent("download");
      await trigger(); const download = await downloadPromise;
      const chunks = []; for await (const chunk of await download.createReadStream()) chunks.push(chunk);
      return { text: Buffer.concat(chunks).toString("utf8"), filename: download.suggestedFilename() };
    };
    await round.getByRole("tab", { name: "② API 原始请求", exact: true }).click();
    assert.equal(await round.getByRole("button", { name: "格式化显示", exact: true }).getAttribute("aria-pressed"), "true");
    const formattedRequest = await round.locator(".debug-raw").textContent();
    assert.ok(formattedRequest.startsWith('{\n  "model": "deepseek-chat",'));
    assert.match(formattedRequest, /小夏喜欢天文和散步。\n\s+今天在教室复习函数。\n\s+课后去公园散步。/);
    assert.ok(formattedRequest.includes('"path": "C:\\\\notes\\\\new.json"'));
    assert.ok(formattedRequest.includes('"literal": "\\\\n"'));
    assert.equal(await round.locator("img").count(), 0, "Formatted bodies render untrusted markup as text");
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, "Long formatted JSON wraps on desktop");
    if (process.env.LIVING_WORLD_RAW_DEBUG_SCREENSHOT) await round.screenshot({ path: process.env.LIVING_WORLD_RAW_DEBUG_SCREENSHOT, style: "#notice { visibility: hidden !important; }" });
    const requestRoot = rootFolds(round).first();
    const messageArray = requestRoot.locator(":scope > .debug-json-children > .debug-json-node").first();
    const messageObjects = messageArray.locator(":scope > .debug-json-children > .debug-json-node");
    const firstMessage = messageObjects.first();
    await foldToggle(firstMessage).click();
    assert.equal(await firstMessage.locator(":scope > .debug-json-children").isVisible(), false);
    assert.equal(await messageObjects.nth(1).locator(":scope > .debug-json-children").isVisible(), true, "Collapsing a message leaves its sibling visible");
    await foldToggle(messageArray).click();
    assert.ok((await round.locator(".debug-raw").innerText()).includes('"messages": […]'), "Collapsed arrays retain their field name");
    await foldToggle(messageArray).focus(); await page.keyboard.press("Enter");
    assert.equal(await foldToggle(messageArray).getAttribute("aria-expanded"), "true", "Keyboard expands the parent");
    assert.equal(await foldToggle(firstMessage).getAttribute("aria-expanded"), "false", "Expanding the parent preserves its child's collapsed state");
    await round.getByRole("tab", { name: "① 上下文与信息来源", exact: true }).click();
    await round.getByRole("tab", { name: "② API 原始请求", exact: true }).click();
    assert.equal(await foldToggle(firstMessage).getAttribute("aria-expanded"), "false", "Tab changes retain folding");
    await round.getByRole("tab", { name: "③ API 原始返回", exact: true }).click();
    assert.equal(await round.locator('.debug-json-toggle[aria-expanded="false"]').count(), 0, "Response folds are independent from request folds");
    await foldToggle(rootFolds(round).first()).click();
    await round.getByRole("tab", { name: "② API 原始请求", exact: true }).click();
    await round.locator('[name="debug_call"]').selectOption("1");
    assert.equal(await round.locator('.debug-json-toggle[aria-expanded="false"]').count(), 0, "Another HTTP call starts expanded");
    await foldToggle(rootFolds(round).first()).click();
    await round.locator('[name="debug_call"]').selectOption("0");
    assert.equal(await foldToggle(requestRoot).getAttribute("aria-expanded"), "true");
    assert.equal(await foldToggle(firstMessage).getAttribute("aria-expanded"), "false", "Returning to an HTTP call restores its own folds");
    await round.getByRole("tab", { name: "③ API 原始返回", exact: true }).click();
    assert.equal(await foldToggle(rootFolds(round).first()).getAttribute("aria-expanded"), "false", "Request navigation does not alter the response's folds");
    await round.getByRole("button", { name: "全部展开", exact: true }).click();
    await round.getByRole("tab", { name: "② API 原始请求", exact: true }).click();
    if (process.env.LIVING_WORLD_JSON_FOLD_SCREENSHOT) await round.screenshot({ path: process.env.LIVING_WORLD_JSON_FOLD_SCREENSHOT, style: "#notice { visibility: hidden !important; }" });
    // Formatting is display-only, including while downloading or copying.
    const formattedDownload = await downloadedText(() => round.getByRole("button", { name: "下载请求原文", exact: true }).click());
    assert.equal(formattedDownload.text, await page.evaluate(() => window.rawFixture.firstRequest));
    await round.getByRole("button", { name: "原文", exact: true }).click();
    assert.equal(await round.locator(".debug-raw").textContent(), await page.evaluate(() => window.rawFixture.firstRequest));
    const firstDownload = await downloadedText(() => round.getByRole("button", { name: "下载请求原文", exact: true }).click());
    assert.equal(firstDownload.text, await page.evaluate(() => window.rawFixture.firstRequest));
    assert.ok(firstDownload.filename.endsWith("-request.json"));
    await round.getByRole("button", { name: "格式化显示", exact: true }).click();
    assert.equal(await foldToggle(firstMessage).getAttribute("aria-expanded"), "false", "Switching through original mode retains nested folds");
    await round.getByRole("button", { name: "全部收起", exact: true }).click();
    assert.equal(await round.locator(".debug-raw").innerText(), "{…}");
    await round.getByRole("button", { name: "复制请求原文", exact: true }).click();
    await page.locator("#editor[open]").waitFor();
    assert.equal(await page.locator('#editor [name="copy"]').inputValue(), firstDownload.text);
    await page.locator("#editor-cancel").click();
    await round.getByRole("button", { name: "全部展开", exact: true }).click();
    assert.equal(await round.locator(".debug-raw").textContent(), formattedRequest);
    await round.getByRole("button", { name: "原文", exact: true }).click();
    await round.getByRole("tab", { name: "③ API 原始返回", exact: true }).click();
    assert.equal(await round.getByRole("button", { name: "格式化显示", exact: true }).getAttribute("aria-pressed"), "true", "Request and response display preferences are independent");
    await round.getByRole("button", { name: "原文", exact: true }).click();
    assert.equal(await round.locator(".debug-raw").textContent(), await page.evaluate(() => window.rawFixture.firstResponse));
    const responseDownload = await downloadedText(() => round.getByRole("button", { name: "下载返回原文", exact: true }).click());
    assert.equal(responseDownload.text, await page.evaluate(() => window.rawFixture.firstResponse));
    assert.ok(responseDownload.text.includes("不得丢弃这个未知字段"));
    await round.getByRole("tab", { name: "④ 回复阅读版", exact: true }).click();
    await round.getByRole("heading", { name: "模型请求调用的工具", exact: true }).waitFor();
    await round.locator('[name="debug_call"]').selectOption("1");
    await round.getByRole("heading", { name: "回复正文", exact: true }).waitFor();
    await round.getByRole("heading", { name: "接口返回的推理内容", exact: true }).waitFor();
    await round.getByRole("heading", { name: "实际聊天发送", exact: true }).waitFor();
    assert.ok((await round.innerText()).includes("第二段发送未确认"));
    await round.getByRole("tab", { name: "② API 原始请求", exact: true }).click();
    assert.equal(await round.locator(".debug-raw").textContent(), await page.evaluate(() => window.rawFixture.secondRequest));
    await round.getByRole("tab", { name: "③ API 原始返回", exact: true }).click();
    assert.equal(await round.locator(".debug-raw").textContent(), await page.evaluate(() => window.rawFixture.secondResponse));
    await round.getByRole("tab", { name: "① 上下文与信息来源", exact: true }).click();
    assert.equal(await sourceCards.first().getAttribute("open"), null, "Source collapse state survives tab and request changes");
    await round.locator('[name="debug_call"]').selectOption("0");
    assert.equal(await sourceCards.first().getAttribute("open"), null, "Changing requests within the source view retains disclosure state");
    if (process.env.LIVING_WORLD_DEBUG_SCREENSHOT) await round.screenshot({ path: process.env.LIVING_WORLD_DEBUG_SCREENSHOT, style: "#notice { visibility: hidden !important; }" });
    const stream = page.locator('.debug-round[data-turn="stream-1"]');
    await page.locator('[name="debug_round"]').selectOption("stream-1");
    await stream.getByRole("heading", { name: "没有可用的信息来源清单", exact: true }).waitFor();
    await stream.getByRole("tab", { name: "③ API 原始返回", exact: true }).click();
    assert.ok((await stream.locator(".debug-raw").textContent()).includes('data: {\ndata:   "choices": ['));
    assert.ok((await stream.locator(".debug-raw").textContent()).endsWith("data: [DONE]\n\n"));
    assert.equal(await rootFolds(stream).count(), 2, "SSE event JSON roots remain separate");
    await foldToggle(rootFolds(stream).first()).click();
    assert.equal(await foldToggle(rootFolds(stream).nth(1)).getAttribute("aria-expanded"), "true", "Collapsing one event leaves the next expanded");
    await stream.getByRole("button", { name: "全部收起", exact: true }).click();
    assert.equal(await stream.locator(".debug-raw").innerText(), "data: {…}\n\ndata: {…}\n\ndata: [DONE]\n\n");
    const streamDownload = await downloadedText(() => stream.getByRole("button", { name: "下载返回原文", exact: true }).click());
    assert.equal(streamDownload.text, await page.evaluate(() => window.rawFixture.sse));
    assert.ok(streamDownload.filename.endsWith(".sse"));
    await stream.getByRole("button", { name: "原文", exact: true }).click();
    assert.equal(await stream.locator(".debug-raw").textContent(), streamDownload.text);
    await stream.getByRole("tab", { name: "④ 回复阅读版", exact: true }).click();
    await stream.getByText("晚风很舒服", { exact: true }).waitFor();
    assert.ok((await stream.innerText()).includes("合并后的阅读内容"));
    const missing = page.locator('.debug-round[data-turn="unavailable-1"]');
    await page.locator('[name="debug_round"]').selectOption("unavailable-1");
    await missing.getByRole("tab", { name: "② API 原始请求", exact: true }).click();
    await missing.getByRole("heading", { name: "没有捕获 API 原始请求", exact: true }).waitFor();
    assert.equal(await missing.getByRole("button", { name: "下载请求原文", exact: true }).count(), 0);
    const legacy = page.locator('.debug-round[data-turn="debug-1"]');
    await page.locator('[name="debug_round"]').selectOption("debug-1");
    assert.ok((await legacy.innerText()).includes("旧版快照，非 API 原文"));
    await legacy.getByRole("tab", { name: "③ API 原始返回", exact: true }).click();
    assert.equal(await legacy.locator(".debug-raw").count(), 0);
    await legacy.getByRole("tab", { name: "④ 回复阅读版", exact: true }).click();
    assert.equal(await legacy.locator(".debug-activity").count(), 1, "Structured activities have a readable timeline");
    await page.locator('[name="category"]').selectOption("reply.tool");
    assert.equal(await page.locator('.debug-round').count(), 1, "Filtering a tool keeps its whole conversation round");
    assert.equal(await page.locator('.debug-round [name="debug_call"] option').count(), 2);
    await page.locator('[name="category"]').selectOption("");
    await round.locator('[name="debug_call"]').selectOption("0");
    await page.evaluate((contract) => {
      window.regularDebugFixture = { views: window.fixture.debug_views, records: window.fixture.debug_records };
      window.fixture.debug_views = contract.views; window.fixture.debug_records = contract.records;
    }, backendContract);
    await page.getByRole("button", { name: "刷新数据", exact: true }).click();
    await page.getByText("数据已刷新", { exact: true }).waitFor();
    const contractChat = page.locator('.debug-round[data-turn="contract-chat"]');
    assert.equal(await page.locator('.debug-round').count(), 1);
    await contractChat.getByText("契约来源清单", { exact: true }).waitFor();
    await contractChat.getByText("角色补充资料：喜欢观察星空。", { exact: true }).waitFor();
    await contractChat.getByRole("tab", { name: "④ 回复阅读版", exact: true }).click();
    await contractChat.getByText("契约测试的真实阅读正文", { exact: true }).waitFor();
    await contractChat.getByRole("heading", { name: "工具实际返回", exact: true }).waitFor();
    await contractChat.getByText("工具真实契约返回资料", { exact: true }).waitFor();
    await contractChat.getByRole("heading", { name: "AstrBot 采用的回复", exact: true }).waitFor();
    await contractChat.getByText("宿主最终采用的契约回复", { exact: true }).waitFor();
    await contractChat.getByText("实际发送的契约正文", { exact: true }).waitFor();
    await contractChat.getByText("fixture-image.png", { exact: true }).waitFor();
    await contractChat.getByRole("tab", { name: "② API 原始请求", exact: true }).click();
    await contractChat.getByRole("button", { name: "原文", exact: true }).click();
    assert.equal(await contractChat.locator(".debug-raw").textContent(), backendContract.views[0].calls[0].request_body);
    await contractChat.getByRole("tab", { name: "③ API 原始返回", exact: true }).click();
    await contractChat.getByRole("button", { name: "原文", exact: true }).click();
    assert.equal(await contractChat.locator(".debug-raw").textContent(), backendContract.views[0].calls[0].response_body);
    await contractChat.getByRole("tab", { name: "④ 回复阅读版", exact: true }).click();
    if (process.env.LIVING_WORLD_BACKEND_DEBUG_SCREENSHOT) await page.screenshot({ path: process.env.LIVING_WORLD_BACKEND_DEBUG_SCREENSHOT, fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    for (const label of ["① 上下文与信息来源", "② API 原始请求", "③ API 原始返回", "④ 回复阅读版"]) {
      await contractChat.getByRole("tab", { name: label, exact: true }).click();
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, `Backend contract stays within mobile width: ${label}`);
    }
    if (process.env.LIVING_WORLD_BACKEND_DEBUG_MOBILE_SCREENSHOT) await page.screenshot({ path: process.env.LIVING_WORLD_BACKEND_DEBUG_MOBILE_SCREENSHOT, fullPage: true });
    await page.setViewportSize({ width: 1600, height: 1050 });
    const contractPlan = page.locator('.debug-round[data-turn="contract-plan"]');
    await page.locator('[name="debug_round"]').selectOption("contract-plan");
    await contractPlan.getByRole("tab", { name: "④ 回复阅读版", exact: true }).click();
    await contractPlan.getByRole("heading", { name: "正式日程采用结果", exact: true }).waitFor();
    await contractPlan.getByRole("heading", { name: "正式采用的数学课", exact: true }).waitFor();
    const contractUnsupported = page.locator('.debug-round[data-turn="contract-unsupported"]');
    await page.locator('[name="debug_round"]').selectOption("contract-unsupported");
    await contractUnsupported.getByRole("tab", { name: "② API 原始请求", exact: true }).click();
    await contractUnsupported.getByText("当前提供商的 HTTP 原文捕获尚未适配", { exact: true }).waitFor();
    assert.equal(await contractUnsupported.getByRole("button", { name: "下载请求原文", exact: true }).count(), 0);
    const contractLegacy = page.locator('.debug-round[data-turn="contract-legacy"]');
    await page.locator('[name="debug_round"]').selectOption("contract-legacy");
    await contractLegacy.getByText("旧版输入快照（非 API 原文）", { exact: true }).waitFor();
    await contractLegacy.getByRole("tab", { name: "④ 回复阅读版", exact: true }).click();
    await contractLegacy.getByText("旧版 reply 字段的返回正文", { exact: true }).waitFor();
    await page.evaluate(() => {
      window.fixture.life_days[0].full_request._debug_record_id = "contract-plan";
    });
    await page.getByRole("button", { name: "刷新数据", exact: true }).click();
    await page.getByText("数据已刷新", { exact: true }).waitFor();

};
