const assert = require("node:assert/strict");
module.exports = async (page, go) => {
    await go("character", "drives");
    await page.locator('[name="drive_meter"]').waitFor();
    assert.equal(await page.locator(".drive-status-cards > .card").count(), 2);
    assert.equal(await page.getByRole("tab", { selected: true }).count(), 1);
    assert.equal(await page.locator(".drive-stage").count(), 3);
    assert.equal(await page.locator('.drive-status-cards [data-drive="energy"] .drive-value').innerText(), "75 / 100");
    assert.equal(await page.locator('[name="drive.value"]').inputValue(), "0");
    await page.locator('[name="drive.growth_per_hour"]').fill("12.5");
    await page.locator('[name="drive.costs.social"]').fill("0");
    await page.locator('[name="drive.value"]').fill("81.75");
    await page.locator('[name="drive_meter"]').selectOption("energy");
    assert.equal(await page.locator('[name="drive.costs.news"]').inputValue(), "10");
    assert.equal(await page.locator('[name="drive.costs.search"]').inputValue(), "10");
    await page.locator('[name="drive_meter"]').selectOption("loneliness");
    assert.equal(await page.locator('[name="drive_meter"]').inputValue(), "loneliness");
    assert.equal(await page.locator('[name="drive.growth_per_hour"]').inputValue(), "12.5", "Switching tabs retains drafts");
    await page.getByRole("button", { name: "应用当前值", exact: true }).click();
    await page.getByText("当前值已应用，参数与阶段草稿继续保留", { exact: true }).waitFor();
    assert.equal(await page.locator('.drive-status-cards [data-drive="loneliness"] .drive-thought').innerText(), "必须聊天。");
    assert.deepEqual(await page.evaluate(() => window.calls.findLast((call) => call.body?.action === "set_drive_value").body), { action: "set_drive_value", id: "loneliness", value: 81.75 });
    assert.equal(await page.evaluate(() => window.fixture.drives.meters.loneliness.config.growth_per_hour), 10, "Applying a value must not save rate drafts");
    await page.evaluate(() => { window.fixture.drives.meters.loneliness.value = 83.8; window.refreshDriveFixture(); });
    await page.getByRole("button", { name: "刷新数据", exact: true }).click();
    await page.getByText("数值已刷新，未保存的修改继续保留", { exact: true }).waitFor();
    assert.equal(await page.locator("#editor").isVisible(), false);
    assert.equal(await page.locator('[name="drive.growth_per_hour"]').inputValue(), "12.5");
    assert.equal(await page.locator('.drive-status-cards [data-drive="loneliness"] .drive-value').innerText(), "83 / 100");
    await page.locator('[name="drive.value"]').fill("12");
    await page.locator('[name="drive.growth_per_hour"]').focus();
    await page.evaluate(async () => { window.fixture.drives.meters.loneliness.value = 84.9; window.refreshDriveFixture(); await window.driveRefreshTick(); });
    assert.equal(await page.locator('[name="drive.value"]').inputValue(), "12", "Automatic refresh must preserve a manual-value draft");
    assert.equal(await page.locator('[name="drive.growth_per_hour"]').evaluate((node) => node === document.activeElement), true, "Status-only refresh preserves editor focus");
    assert.equal(await page.locator('.drive-status-cards [data-drive="loneliness"] .drive-value').innerText(), "84 / 100");
    await page.getByRole("button", { name: "拆分第 1 阶段", exact: true }).click();
    assert.equal(await page.locator(".drive-stage").count(), 4);
    assert.equal(await page.locator('[name="drive.stage.0.max"]').inputValue(), "20");
    await page.locator('[name="drive.stage.0.max"]').fill("15"); await page.locator('[name="drive.stage.0.max"]').press("Tab");
    assert.match(await page.locator(".drive-stage").nth(1).innerText(), /阶段 2 · 16—40/);
    await page.getByRole("button", { name: "删除第 1 阶段", exact: true }).click();
    assert.match(await page.locator(".drive-stage").first().innerText(), /阶段 1 · 0—40/);
    await page.getByRole("button", { name: "删除第 2 阶段", exact: true }).click();
    assert.match(await page.locator(".drive-stage").first().innerText(), /阶段 1 · 0—80/);
    await page.getByRole("button", { name: "拆分第 1 阶段", exact: true }).click();
    await page.locator('[name="drive.stage.0.max"]').fill("0"); await page.locator('[name="drive.stage.0.max"]').press("Tab");
    assert.equal(await page.getByRole("button", { name: "拆分第 1 阶段", exact: true }).isDisabled(), true, "A one-value stage cannot split");
    await page.locator('[name="drive.stage.0.max"]').fill("40"); await page.locator('[name="drive.stage.0.max"]').press("Tab");
    await page.locator('[name="drive.stage.0.max"]').fill("81"); await page.locator('[name="drive.stage.0.max"]').dispatchEvent("change");
    assert.equal(await page.locator('[name="drive.stage.0.max"]').inputValue(), "40", "Overlapping stage boundaries are rejected");
    await page.getByRole("button", { name: "删除第 1 阶段", exact: true }).click();
    await page.getByRole("button", { name: "删除第 1 阶段", exact: true }).click();
    assert.equal(await page.getByRole("button", { name: "删除第 1 阶段", exact: true }).isDisabled(), true);
    assert.equal(await page.locator('[name="drive.stage.0.max"]').getAttribute("readonly"), "");
    await page.getByRole("button", { name: "拆分第 1 阶段", exact: true }).click();
    await page.getByRole("button", { name: "拆分第 1 阶段", exact: true }).click();
    await page.locator('[name="drive.stage.0.max"]').fill("40"); await page.locator('[name="drive.stage.0.max"]').press("Tab");
    await page.locator('[name="drive.stage.1.max"]').fill("80"); await page.locator('[name="drive.stage.1.max"]').press("Tab");
    for (const [index, text] of ["不是很想聊天。", "想偷偷看一眼 QQ 聊天。", "必须聊天。<img src=x onerror=window.driveXss=true>"].entries()) await page.locator(`[name="drive.stage.${index}.text"]`).fill(text);
    await page.evaluate(() => { window.failNext = true; });
    await page.getByRole("button", { name: "保存设置", exact: true }).click();
    await page.getByText("测试来源暂时不可用", { exact: true }).waitFor();
    assert.equal(await page.locator('[name="drive.growth_per_hour"]').inputValue(), "12.5", "Failed save retains the configuration draft");
    await page.getByRole("button", { name: "保存设置", exact: true }).click();
    await page.getByText("参数与阶段已保存，当前值继续按运行规则变化", { exact: true }).waitFor();
    const driveSaved = await page.evaluate(() => window.calls.findLast((call) => call.body?.action === "save_drive_settings").body);
    assert.equal(Object.hasOwn(driveSaved, "value"), false); assert.equal(driveSaved.config.growth_per_hour, 12.5); assert.equal(driveSaved.config.costs.social, 0);
    assert.deepEqual(driveSaved.config.stages.map((stage) => stage.max), [40, 80, 100]);
    assert.equal(await page.evaluate(() => window.fixture.drives.meters.loneliness.value), 84.9, "Saving configuration does not apply the manual-value draft");
    assert.equal(await page.locator('[name="drive.value"]').inputValue(), "12");
    assert.equal(await page.locator(".drive-thought img").count(), 0); assert.equal(await page.evaluate(() => window.driveXss), undefined);
    await page.locator('[name="drive.stage.2.text"]').fill("必须聊天。");
    await page.getByRole("button", { name: "保存设置", exact: true }).click();
    await page.getByRole("button", { name: "应用当前值", exact: true }).click();
    await page.locator('[name="drive_meter"]').selectOption("energy");
    await page.locator('[name="drive.costs.news"]').fill("7.5"); await page.locator('[name="drive.costs.search"]').fill("15");
    await page.getByRole("button", { name: "保存设置", exact: true }).click();
    assert.deepEqual(await page.evaluate(() => window.fixture.drives.meters.energy.config.costs), { news: 7.5, search: 15 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, "No desktop meter overflow");
    if (process.env.LIVING_WORLD_DRIVES_SCREENSHOT) await page.locator("#content").screenshot({ path: process.env.LIVING_WORLD_DRIVES_SCREENSHOT, style: "#notice { visibility: hidden !important; }" });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('[name="drive_meter"]').selectOption("loneliness");
    await page.getByRole("button", { name: "拆分第 1 阶段", exact: true }).click();
    await page.getByRole("button", { name: "删除第 2 阶段", exact: true }).click();
    await page.getByRole("button", { name: "保存设置", exact: true }).click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, "No mobile meter overflow");
    if (process.env.LIVING_WORLD_DRIVES_MOBILE_SCREENSHOT) await page.locator("#content").screenshot({ path: process.env.LIVING_WORLD_DRIVES_MOBILE_SCREENSHOT, style: "#notice { visibility: hidden !important; }" });
    await page.setViewportSize({ width: 1600, height: 1050 });
    await page.evaluate(() => { window.fixture.settings.modules.drives = false; window.refreshDriveFixture(); });
    await page.getByRole("button", { name: "刷新数据", exact: true }).click();
    assert.equal(await page.locator(".drive-status-cards").getByText("已暂停", { exact: true }).count(), 2);
    assert.equal(await page.locator(".drive-status-cards").getByText("模块已暂停，下次细化不注入这项想法。", { exact: true }).count(), 2);
    await page.locator('[name="drive.value"]').fill("40.99"); await page.getByRole("button", { name: "应用当前值", exact: true }).click();
    assert.match(await page.locator('.drive-status-cards [data-drive="loneliness"]').innerText(), /当前阶段 0—40/);
    await page.evaluate(() => { window.fixture.settings.modules.drives = true; window.refreshDriveFixture(); });
    await page.getByRole("button", { name: "刷新数据", exact: true }).click();
};
