/* Pure edits must finish even when the expensive full-state endpoint is unavailable. */
const assert = require("node:assert/strict");
module.exports = async (page, go) => {
  const field = name => page.locator(`[name="${name}"]`);
  const click = name => page.getByRole("button", { name, exact: true }).click();
  const done = async () => {
    await page.getByText("操作已完成，请查看执行结果", { exact: true }).waitFor();
    await page.locator('#content[aria-busy="false"]').waitFor();
  };
  const original = await page.evaluate(() => ({ fixture: structuredClone(window.fixture), calls: structuredClone(window.calls) }));
  const template = original.fixture.debug.templates[0];
  await go("context", "templates", { task: template.task });
  await page.evaluate(() => { window.rejectStateRead = true; });
  await field("template").fill("新的公共模板；JSON: {\"mode\":\"test\"}");
  await page.evaluate(() => { window.failNext = true; });
  await click("保存此任务模板");
  await page.getByText("测试来源暂时不可用", { exact: true }).waitFor();
  assert.match(await field("template").inputValue(), /新的公共模板/);
  await click("保存此任务模板"); await done();
  await go("overview", "current"); await go("context", "templates", { task: template.task });
  assert.match(await field("template").inputValue(), /新的公共模板/);
  await field("template").fill("恢复失败也应保留的草稿");
  await page.evaluate(() => { window.failNext = true; });
  await click("恢复默认模板");
  await page.getByText("测试来源暂时不可用", { exact: true }).waitFor();
  assert.equal(await field("template").inputValue(), "恢复失败也应保留的草稿");
  await click("恢复默认模板"); await done();
  assert.equal(await field("template").inputValue(), template.default_template);
  await go("overview", "current"); await go("context", "templates", { task: template.task });
  assert.equal(await field("template").inputValue(), template.default_template);
  await go("chat", "reply");
  await field("reply.private_prompt").fill("仅修改私聊提示词");
  await click("保存回复与插话设置");
  await page.getByText("设置已保存并应用，已有记录继续保留", { exact: true }).waitFor();
  await go("overview", "current"); await go("chat", "reply");
  assert.equal(await field("reply.private_prompt").inputValue(), "仅修改私聊提示词");
  await go("character", "state"); await field("mood").fill("心情保存即更新");
  await click("保存生活状态"); await done();
  await go("overview", "current");
  await page.getByText("心情保存即更新", { exact: true }).waitFor();
  await go("schedule", "timeline");
  await page.getByLabel("日程日期").fill(await page.evaluate(() => window.testTomorrow));
  await page.getByLabel("日程日期").dispatchEvent("change");
  await click("批量调整未来活动");
  const payload = JSON.parse(await field("json").inputValue());
  payload.updates[0].changes.title = "JSON 保存后立即显示的新标题";
  await field("json").fill(JSON.stringify(payload));
  await page.evaluate(() => { window.failNext = true; });
  await page.locator("#editor-submit").click();
  await page.getByText("测试来源暂时不可用", { exact: true }).waitFor();
  assert.match(await field("json").inputValue(), /JSON 保存后立即显示/);
  await page.locator("#editor-submit").click(); await done();
  await page.getByText("JSON 保存后立即显示的新标题", { exact: true }).waitFor();
  await click("编辑"); await field("title").fill("单条活动也立即显示");
  await page.locator("#editor-submit").click(); await done();
  await page.getByText("单条活动也立即显示", { exact: true }).waitFor();
  const calls = await page.evaluate(start => window.calls.slice(start), original.calls.length);
  assert.equal(calls.some(call => call.method === "GET"), false);
  assert.deepEqual([...new Set(calls.filter(call => call.endpoint === "action").map(call => call.body.action))], ["save_template", "reset_template", "update_state", "update_activities", "update_activity"]);
  await page.evaluate(original => { window.rejectStateRead = false; window.fixture = original.fixture; window.calls = original.calls; }, original);
  await click("刷新数据");
  await go("schedule", "timeline");
  await page.getByLabel("日程日期").fill(original.fixture.life_days[0].date);
  await page.getByLabel("日程日期").dispatchEvent("change");
};
