/* Unified profiles, controls and usage through the desktop bridge. */
const assert = require("node:assert/strict");
module.exports = async (page, go, field, click, save, shot) => {
  await go("context", "usage");
  await field("context_usage.limits.memory.self").fill("8");
  await field("context_usage.people_limit").fill("2");
  await page.locator(".context-usage-row").first().getByRole("button", { name: /来源$/ }).click();
  await page.locator("#source-index").getByRole("button", { name: "07 记忆与日记 → 记忆与画像", exact: true }).click();
  await page.locator('#section-panel[data-page="memory"][data-section="records"]').waitFor();
  assert.equal(await field("memory.attribute").locator("option").count(), 6);
  await click("返回上下文用量");
  assert.equal(await field("context_usage.limits.memory.self").inputValue(), "8");
  await page.evaluate(() => { window.failNext = true; }); await click("保存上下文用量");
  await page.getByText("测试来源暂时不可用", { exact: true }).waitFor();
  await click("刷新数据");
  await go("memory", "records"); await go("context", "usage");
  assert.equal(await field("context_usage.people_limit").inputValue(), "2");
  const beforeSave = await page.evaluate(() => { window.rejectStateRead = true; return window.calls.length; });
  await save("保存上下文用量");
  const saveCalls = await page.evaluate(index => { window.rejectStateRead = false; return window.calls.slice(index); }, beforeSave);
  assert.deepEqual(saveCalls.map(call => `${call.method} ${call.endpoint}`), ["POST settings"]);
  await go("memory", "records"); await go("context", "usage");
  assert.equal(await field("context_usage.people_limit").inputValue(), "2");
  const usage = await page.evaluate(() => window.calls.findLast(call => call.endpoint === "settings" && call.method === "POST").body);
  assert.deepEqual(Object.keys(usage), ["context_usage"]);
  assert.equal(usage.context_usage.version, 2);
  assert.deepEqual(usage.context_usage.limits, { "memory.self": 8, "memory.people": 5, "memory.related": 10, "memory.recent": 5, weather: 1 });
  assert.equal(usage.context_usage.people_limit, 2);
  assert.equal(Object.hasOwn(usage.context_usage, "brief_max_chars"), false);
  assert.match(await page.locator(".context-usage-total").textContent(), /34 条/);
  const savedCalls = await page.evaluate(() => window.calls.length);
  await click("恢复初始用量");
  assert.match(await page.locator(".context-usage-total").textContent(), /36 条/);
  assert.equal(await page.evaluate(() => window.calls.length), savedCalls);
  await field("context_usage.people_limit").fill("0");
  assert.match(await page.locator(".context-usage-total").textContent(), /21 条/);
  assert.equal(await page.locator(".context-usage-row").count(), 5);
  assert.equal(await page.locator(".context-usage-row .layout-source").count(), 5);
  assert.ok((await page.locator(".context-usage-row").evaluateAll(rows => rows.map(row => row.getBoundingClientRect().height))).every(height => height <= 44));
  await shot("context-usage-desktop");

  await go("memory", "records");
  await page.evaluate(() => { window.fixture.memories.push({ id: "legacy-memory", text: "旧格式尚待提炼", kind: "event", scope: "global" }); });
  await click("刷新数据");
  assert.equal(await page.locator('[data-record-id="legacy-memory"]').count(), 0);
  await page.getByRole("button", { name: "查看整理进度", exact: true }).waitFor();
  await page.evaluate(() => { window.fixture.memories = window.fixture.memories.filter(row => row.id !== "legacy-memory"); });
  await click("刷新数据");
  await field("memory.profile").selectOption("self:旧名字");
  assert.equal(await page.locator(".compact-record-row").count(), 0);
  await field("memory.profile").selectOption("person:42");
  assert.equal(await field("memory.profile").locator('option:checked').textContent(), "朋友（QQ 42）（2 条）");
  assert.equal(await page.locator(".compact-record-row").count(), 2);
  await field("memory.attribute").selectOption("事实属性");
  assert.equal(await page.locator(".compact-record-row").count(), 1);
  await field("memory.attribute").selectOption("");
  await page.locator('[data-record-id="m1"]').getByRole("button", { name: "编辑", exact: true }).click();
  assert.match(await page.locator("#editor-body").textContent(), /编辑保留原有场合与人物归属/);
  assert.match(await page.locator("#editor-body").textContent(), /朋友（QQ 42）/);
  assert.doesNotMatch(await page.locator("#editor-body").textContent(), /QQ qq:/i);
  assert.equal(await page.locator('#editor [name="scope"]').count(), 0);
  await page.locator('#editor [name="text"]').fill("更新后的流星雨约定");
  await page.locator('#editor [name="reasoning"]').fill("私聊中确认日期。<script>window.memoryXss=1</script>");
  await page.locator('#editor [name="tags"]').fill("流星雨\n天文");
  await page.evaluate(() => { window.failNext = true; }); await page.locator("#editor-submit").click();
  await page.getByText("测试来源暂时不可用", { exact: true }).waitFor();
  assert.equal(await page.locator('#editor [name="text"]').inputValue(), "更新后的流星雨约定");
  await page.locator("#editor-submit").click(); await page.locator("#editor").waitFor({ state: "hidden" });
  const changed = await page.evaluate(() => window.calls.findLast(call => call.body?.action === "memory.update").body);
  assert.deepEqual(changed.patch.tags, ["流星雨", "天文"]);
  assert.equal(changed.patch.attribute, "活跃项目");
  await page.locator('[data-record-id="m1"] .record-open').click();
  assert.match(await page.locator("#editor-body").textContent(), /私聊中确认日期/);
  assert.equal(await page.evaluate(() => window.memoryXss), undefined);
  await page.locator("#editor-cancel").click();
  await page.evaluate(() => { window.rejectStateRead = true; });
  await page.locator('[data-record-id="m1"]').getByRole("button", { name: "变更记录", exact: true }).click();
  await page.locator("#editor[open]").waitFor();
  assert.match(await page.locator("#editor-body").textContent(), /约好了明天一起聊流星雨/);
  await page.locator("#editor-cancel").click();
  await page.evaluate(() => { window.rejectStateRead = false; });
  await field("memory.profile").selectOption("");
  await shot("memory-profiles-desktop");

  await go("memory", "settings");
  assert.equal(await field("memory.forgetting_enabled").isChecked(), false);
  assert.equal(await field("memory.chat_batch_rounds").inputValue(), "5");
  assert.equal(await field("memory.chat_idle_minutes").inputValue(), "10");
  assert.equal(await field("memory.low_decay_days").inputValue(), "3");
  await field("memory.chat_batch_rounds").fill("4");
  await field("memory.forgetting_enabled").check();
  await go("context", "usage"); await go("memory", "settings");
  assert.equal(await field("memory.chat_batch_rounds").inputValue(), "4");
  await page.evaluate(() => { window.failNext = true; }); await click("保存提炼与遗忘设置");
  await page.getByText("测试来源暂时不可用", { exact: true }).waitFor(); await click("刷新数据");
  assert.equal(await field("memory.forgetting_enabled").isChecked(), true);
  await save("保存提炼与遗忘设置");
  const config = await page.evaluate(() => window.calls.findLast(call => call.endpoint === "settings" && call.method === "POST").body);
  assert.deepEqual(Object.keys(config), ["memory"]);
  assert.equal(config.memory.chat_batch_rounds, 4);
  assert.equal(config.memory.chat_idle_seconds, 600);
  assert.equal(config.memory.low_decay_seconds, 259200);
  assert.equal(config.memory.forgetting_enabled, true);
  assert.equal(Object.hasOwn(config.memory, "chat_idle_minutes"), false);
  await click("处理待提炼材料");
  assert.equal(await page.evaluate(() => window.calls.at(-2).body.action), "memory.process");
  await shot("memory-settings-desktop");
};
