/* Unified profiles, controls and usage through the desktop bridge. */
const assert = require("node:assert/strict");
module.exports = async (page, go, field, click, save, shot) => {
  await go("context", "usage");
  await field("context_usage.limits.memory.self").fill("8");
  await field("context_usage.people_limit").fill("2");
  await page.locator(".context-usage-row").first().getByRole("button", { name: /来源$/ }).click();
  await page.locator("#source-index").getByRole("button", { name: "07 记忆与日记 → 记忆与画像", exact: true }).click();
  await page.locator('#section-panel[data-page="memory"][data-section="records"]').waitFor();
  await page.locator(".memory-profile-card").first().waitFor();
  await click("返回上下文用量");
  assert.equal(await field("context_usage.limits.memory.self").inputValue(), "8");
  await page.evaluate(() => { window.failNext = true; }); await click("保存上下文用量");
  await page.getByText("测试来源暂时不可用", { exact: true }).waitFor();
  await click("刷新数据");
  await go("memory", "records"); await go("context", "usage");
  assert.equal(await field("context_usage.people_limit").inputValue(), "2");
  const beforeSave = await page.evaluate(() => { window.rejectStateRead = true; return window.calls.length; });
  await save("保存上下文用量");
  const saveCalls = await page.evaluate(index => { window.rejectStateRead = false; return window.calls.slice(index); }, beforeSave);
  assert.deepEqual(saveCalls.map(call => `${call.method} ${call.endpoint}`), ["POST settings"]);
  await go("memory", "records"); await go("context", "usage");
  assert.equal(await field("context_usage.people_limit").inputValue(), "2");
  const usage = await page.evaluate(() => window.calls.findLast(call => call.endpoint === "settings" && call.method === "POST").body);
  assert.deepEqual(Object.keys(usage), ["context_usage"]);
  assert.equal(usage.context_usage.version, 2);
  assert.deepEqual(usage.context_usage.limits, { "memory.self": 8, "memory.people": 5, "memory.related": 10, "memory.recent": 5, weather: 1 });
  assert.equal(usage.context_usage.people_limit, 2);
  assert.equal(Object.hasOwn(usage.context_usage, "brief_max_chars"), false);
  assert.match(await page.locator(".context-usage-total").textContent(), /34 条/);
  const savedCalls = await page.evaluate(() => window.calls.length);
  await click("恢复初始用量");
  assert.match(await page.locator(".context-usage-total").textContent(), /36 条/);
  assert.equal(await page.evaluate(() => window.calls.length), savedCalls);
  await field("context_usage.people_limit").fill("0");
  assert.match(await page.locator(".context-usage-total").textContent(), /21 条/);
  assert.equal(await page.locator(".context-usage-row").count(), 5);
  assert.equal(await page.locator(".context-usage-row .layout-source").count(), 5);
  assert.ok((await page.locator(".context-usage-row").evaluateAll(rows => rows.map(row => row.getBoundingClientRect().height))).every(height => height <= 44));
  await shot("context-usage-desktop");

  await go("memory", "records");
  await page.locator(".memory-profile-card").first().waitFor();
  assert.equal(await page.locator(".memory-profile-card").count(), 3);
  await page.locator(".memory-profile-card").filter({ hasText: "旧名字" }).click();
  await page.locator(".memory-group-empty").first().waitFor();
  assert.equal(await page.locator(".memory-group-empty").count(), 5);
  assert.equal(await page.getByRole("button", { name: "添加记忆", exact: true }).count(), 0);
  await click("← 返回画像列表");
  await page.locator(".memory-profile-card").filter({ hasText: "朋友" }).click();
  await page.locator('[data-memory-id="m1"]').waitFor();
  assert.equal(await page.locator(".memory-item").count(), 2);
  await field("memory-browser-attribute").selectOption("事实属性");
  await page.locator('[data-memory-id="m1"]').waitFor({ state: "hidden" });
  assert.equal(await page.locator(".memory-item").count(), 1);
  await field("memory-browser-attribute").selectOption("");
  await page.locator('[data-memory-id="m1"]').getByRole("button", { name: "编辑", exact: true }).click();
  const editor = page.locator(".memory-editor");
  assert.match(await editor.textContent(), /保留原归属和场合/);
  assert.equal(await editor.locator('[name="scope"]').count(), 0);
  await editor.locator('[name="text"]').fill("更新后的流星雨约定");
  await editor.locator('[name="reasoning"]').fill("私聊中确认日期。<script>window.memoryXss=1</script>");
  await editor.locator('[name="tags"]').fill("流星雨\n天文");
  await page.evaluate(() => { window.failNext = true; });
  await editor.getByRole("button", { name: "保存记忆", exact: true }).click();
  await editor.getByText("测试来源暂时不可用", { exact: true }).waitFor();
  assert.equal(await editor.locator('[name="text"]').inputValue(), "更新后的流星雨约定");
  await page.evaluate(() => { window.rejectStateRead = true; });
  await editor.getByRole("button", { name: "保存记忆", exact: true }).click();
  await editor.waitFor({ state: "hidden" });
  assert.match(await page.locator('[data-memory-id="m1"]').textContent(), /私聊中确认日期/);
  assert.equal(await page.evaluate(() => window.memoryXss), undefined);
  await page.locator('[data-memory-id="m1"]').getByText("变更记录", { exact: true }).click();
  await page.locator('[data-memory-id="m1"] .memory-version').waitFor();
  assert.match(await page.locator('[data-memory-id="m1"] .memory-version').textContent(), /约好了明天一起聊流星雨/);
  await page.evaluate(() => { window.rejectStateRead = false; });
  await click("← 返回画像列表");
  await shot("memory-profiles-desktop");

  await go("memory", "settings");
  assert.equal(await field("memory.forgetting_enabled").isChecked(), false);
  assert.equal(await field("memory.chat_batch_rounds").inputValue(), "5");
  assert.equal(await field("memory.chat_idle_minutes").inputValue(), "10");
  assert.equal(await field("memory.low_decay_days").inputValue(), "3");
  await field("memory.chat_batch_rounds").fill("4");
  await field("memory.forgetting_enabled").check();
  await go("context", "usage"); await go("memory", "settings");
  assert.equal(await field("memory.chat_batch_rounds").inputValue(), "4");
  await page.evaluate(() => { window.failNext = true; }); await click("保存提炼与遗忘设置");
  await page.getByText("测试来源暂时不可用", { exact: true }).waitFor(); await click("刷新数据");
  assert.equal(await field("memory.forgetting_enabled").isChecked(), true);
  await save("保存提炼与遗忘设置");
  const config = await page.evaluate(() => window.calls.findLast(call => call.endpoint === "settings" && call.method === "POST").body);
  assert.deepEqual(Object.keys(config), ["memory"]);
  assert.equal(config.memory.chat_batch_rounds, 4);
  assert.equal(config.memory.chat_idle_seconds, 600);
  assert.equal(config.memory.low_decay_seconds, 259200);
  assert.equal(config.memory.forgetting_enabled, true);
  assert.equal(Object.hasOwn(config.memory, "chat_idle_minutes"), false);
  await click("处理待提炼材料");
  assert.equal(await page.evaluate(() => window.calls.at(-2).body.action), "memory.process");
  await shot("memory-settings-desktop");
};
